-- Run this in Supabase SQL Editor

create table tickets (
  id bigint generated by default as identity primary key,
  ticket_number text not null UNIQUE, -- UNIQUE constraint prevents duplicate tickets
  client_name text,
  client_phone text,
  client_state text,
  status text default 'reserved', -- 'reserved', 'paid', 'available'
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- ============================================
-- MIGRATION SQL (Run in Supabase SQL Editor)
-- ============================================
-- Step 1: Delete duplicate tickets (keeps the oldest one)
-- DELETE FROM tickets a USING tickets b 
-- WHERE a.id > b.id AND a.ticket_number = b.ticket_number;

-- Step 2: Add UNIQUE constraint
-- ALTER TABLE tickets ADD CONSTRAINT unique_ticket_number UNIQUE (ticket_number);

-- Enable Row Level Security (RLS) is recommended but for this MVP we might start open
alter table tickets enable row level security;

-- Policy: Allow public read access (so everyone can see taken tickets)
create policy "Public tickets are viewable"
  on tickets for select
  using ( true );

-- Policy: Allow public insert (so people can buy tickets)
create policy "Public can insert tickets"
  on tickets for insert
  with check ( true );

-- Policy: Allow public update (for admin, though ideally admin should be authenticated)
-- For simplicity in this v1 without auth, we allow update
create policy "Public can update tickets"
  on tickets for update
  using ( true );
